language: python
python:
- '3.6'
install:
- pip install .
script:
- echo "No tests"
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: GDblvxAKNpdjc8WJVf1FlihkZy6ZGVT+Cibmiy7nfDNCEx6qETlF3Kpy05nXc88NYCF33dCZWsyhZPTZTS7GFRlAeU5fHM17oKcTiA05id8EJ5irYJB7kKaGp0zr+z0XmdkjfXq6d1HZImioyw2ng/so0249e36YT/xLMkEgGwyszh8gcRIsgHa4iwxoNXdo9U7WTmF7ud1A6JVByMcncjePlP2mBvQFFiZ5oeyZrSMmi/iiCK/qVCxQh/y+soAMFAA+eI0mbV+DfkYZO3glCOmrSgkR704EhzCWCZHqCW79u635KQjhT1Vr6NQcqNGxp5m7fhCYjy8nkDoulE4j3CTtsfGr/OYUxNjM3tV3mwmucIDMZZ7l5gMro/Erfc5+RpN+vEwO92d69NVc7O3IG4BMyfmK33fGNe9iwGO+Cd8AJMaTFzXw53Qb4iDJrIqjJzh45IXinlw2XB4tSjiPVPGrcKz5TzubbY0H1oOw/yWSXWpJ0m8cBSuQ6/3XMf/BhyMnogxtGhIZRbXt7OmdktBvfoh+qELuq8qnKKGBvb2ILPzlmuG85+XEm9x6hBVPmCh/thdhFjYgEX1qBNZIvFXYA4veLM95KZuJKmdQMa2ygXthygGLHKLgoXotECruF/jXC1u4Skn1rNDUq0Rj9P+N2KhG98E0kqGjHdDdajc=
  on:
    repo: deep-compute/gitkanban
    tags: true

- provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: "deepcompute"
  password:
    secure: "cfoZUiCmZx24WfJHDBa7AUfFQfTmqOGQQchKv9PlNYW20bN5D96apT1L5fCiy8aXizcEfy8755e5R3/D19/z7loyUFY/0cwk7dNCcBxSTb9xMtlzytjYiMhBX5hMcJpvKR54ozVoFIk7vdyiKOxG50WnzD8sw9rzsDaZMIWqFHi2PumbpxRpTuTFrTM9XO+N2SST6YByApYAHx3TjBZuo+s8tZMJnLwsldWZLfaJCE4CJ/y2q9ACgTt92iUwgS/WZuhnjNN1ITA1cYYYeFben9FL0L47tIW8o3rVs1iI7C55ia36ifug3dY01Gg+MLtmjrz1q7uyJEWQqw4Ve+DP/HVcgCAban+i3jadz/nyaE0/SRZxu6AEwSicxTMpByHJwfYhQdV3tIJkez2gjYsrDrF+x8cnnVdqyJoAXhyh2TgTwfsy9GKyRneS66TPJP0yyMvjs2kQXUCGcwsGYpar9OnmTLCDOqyW4sEeKyrYT74oVsw4EfetYveglKzsU/+KMf1nosctkG/4aZGG84BmHM4zaup9aEghH44oXd3/WVz25oA2xpda8N608aWTkaWzrewXnTZdXhmOidSeozpmVwAsdtdPpPrD7IKB7hFIjC2nH/yTVJx4IAi/2p2PBkVLm20WNMV/t7eYK4h8WkSH/V9c+x92tjBDKyDVyiIkJLo="
  on:
    branch: master
    tags: true

