language: python
python:
- '3.6'
install:
- pip install .
script:
- echo "No tests"
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: LsEEFkWWq5J6GodJMa/pBkGIBGsT1XwTBTOooMTPoGi3l5+Wr5WpTFeHDDc6m4gNrDQ5TJvhqznpUW5JptXoLtAtd/+CM5XUYJXqb+KoKa1tqZLH4Z6XALFJ4H3jfGw7uX4AkwA2sZJBslCjFJyyxeP7WJhkAcKRzrXxYRQG50wewdu1vEUNyt60CNKyJugr5LxHD0RfcGomY4O/NBolpKR+6PjR7nmaG2lHcFCVq8XYnIFHLTUunkb/znX1pNruCzSqrCC7+Gt8IkaOKIsx+QOcPy9SaukZlMgVI8DAYUN366Mqs9d+m56z0r8ec+2fxCmBiBcjb7K6pbYxL5DpBdfX9I5g6p123vn3QRHbhq8DmT+rCb3xkW+R/9jKXgy+ZNVljeZuVbVZOskrmcVuyP7V74B2jYxAu/h6YxyQkPioCsDQbwCNht8NSaew/b27j/wGPOTEFf0zGmJOxp2FaJLRjTO/b8TXX7HbmO4oKutTrVH9vDwJVA6f0v4UnRaqXgb0mFgect3EiP5z0jcGA4vvy6fyK4suTQdL8ypqqnhVbumaFDz2xogH9CZFr8sPTTvf0+BcHKw70tQFDiektguHYML3K8xYZvCQBp52QNpZU69lrbfJhbG7L0xjczv1N2SGMXf3FxU7RYPMYIeHTWBzvNIg6GqgOAGxFmWgZBY=
  on:
    repo: deep-compute/gitkanban
    tags: true
- provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: "deepcompute"
  password:
    secure: "cfoZUiCmZx24WfJHDBa7AUfFQfTmqOGQQchKv9PlNYW20bN5D96apT1L5fCiy8aXizcEfy8755e5R3/D19/z7loyUFY/0cwk7dNCcBxSTb9xMtlzytjYiMhBX5hMcJpvKR54ozVoFIk7vdyiKOxG50WnzD8sw9rzsDaZMIWqFHi2PumbpxRpTuTFrTM9XO+N2SST6YByApYAHx3TjBZuo+s8tZMJnLwsldWZLfaJCE4CJ/y2q9ACgTt92iUwgS/WZuhnjNN1ITA1cYYYeFben9FL0L47tIW8o3rVs1iI7C55ia36ifug3dY01Gg+MLtmjrz1q7uyJEWQqw4Ve+DP/HVcgCAban+i3jadz/nyaE0/SRZxu6AEwSicxTMpByHJwfYhQdV3tIJkez2gjYsrDrF+x8cnnVdqyJoAXhyh2TgTwfsy9GKyRneS66TPJP0yyMvjs2kQXUCGcwsGYpar9OnmTLCDOqyW4sEeKyrYT74oVsw4EfetYveglKzsU/+KMf1nosctkG/4aZGG84BmHM4zaup9aEghH44oXd3/WVz25oA2xpda8N608aWTkaWzrewXnTZdXhmOidSeozpmVwAsdtdPpPrD7IKB7hFIjC2nH/yTVJx4IAi/2p2PBkVLm20WNMV/t7eYK4h8WkSH/V9c+x92tjBDKyDVyiIkJLo="
  on:
    branch: master
    tags: true
