language: python
python:
- '3.6'
install:
- pip install .
script:
- echo "No tests"
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: NzBKuHBOxaOEsvXoGxwSwwPdTDi8I8DaFXHwpRNBLpxwuTo0fpDhIeMXcnIxlj1EXUtL1QkHOKQgVb7YW7Va/6wVQSrnlGR7gVas07KIeVdIwheh54K+0WtfL6ZxswcRSgoo62meIwxSsgmJRM9KAJqeWUb3KJVRlrrl3MWPo3kyxiGMCyqkayRFiXu1aAiHyPYoCuPysDnYNzYKEKw/326pilbW8/xa7NnKpXIhPUdKzcz4U/d1l0LzI3Rl6GK9sb8gShcH1FRVa3SYIeSi++/VjCgGBHmktnl4La+U+oewZQx56Zq2+3RAznUCLMlMjb9jr98XJq9a1APHmVXcaVMWohba5rWsG/nGtf7/uk0Nb75I18I+EatBHFoLBLPU1lf/dgiEXNaxoGRlS0DnhFJJvZe5JDQeBrwwZZvfslcIJToSIpat7s2kvSIsxOF2juhzXIfxMgMRRXLiYCcduUHWa2VQtMeKPXe7okMH7OonOb0hA0DXif6CNW5e0/H7vQ63T6KHZtHbQLUCAD+3Uy8s263OFGB0Z4zDDyyI9WRBLntyFmFjOEl+rnQc+F+vl9TU65DHtHJFv8XZ1+yakZOSwmPsmVfoTuJ8P1hA4v380GN7qrvInMWhWR6cE+2YVMGHIXQiSqAjqCwJCLivaFJk05qdwWLoCiqxakf8XM4=
  on:
    repo: deep-compute/gitkanban
    tags: true

- provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: "deepcompute"
  password:
    secure: "cfoZUiCmZx24WfJHDBa7AUfFQfTmqOGQQchKv9PlNYW20bN5D96apT1L5fCiy8aXizcEfy8755e5R3/D19/z7loyUFY/0cwk7dNCcBxSTb9xMtlzytjYiMhBX5hMcJpvKR54ozVoFIk7vdyiKOxG50WnzD8sw9rzsDaZMIWqFHi2PumbpxRpTuTFrTM9XO+N2SST6YByApYAHx3TjBZuo+s8tZMJnLwsldWZLfaJCE4CJ/y2q9ACgTt92iUwgS/WZuhnjNN1ITA1cYYYeFben9FL0L47tIW8o3rVs1iI7C55ia36ifug3dY01Gg+MLtmjrz1q7uyJEWQqw4Ve+DP/HVcgCAban+i3jadz/nyaE0/SRZxu6AEwSicxTMpByHJwfYhQdV3tIJkez2gjYsrDrF+x8cnnVdqyJoAXhyh2TgTwfsy9GKyRneS66TPJP0yyMvjs2kQXUCGcwsGYpar9OnmTLCDOqyW4sEeKyrYT74oVsw4EfetYveglKzsU/+KMf1nosctkG/4aZGG84BmHM4zaup9aEghH44oXd3/WVz25oA2xpda8N608aWTkaWzrewXnTZdXhmOidSeozpmVwAsdtdPpPrD7IKB7hFIjC2nH/yTVJx4IAi/2p2PBkVLm20WNMV/t7eYK4h8WkSH/V9c+x92tjBDKyDVyiIkJLo="
  on:
    branch: master
    tags: true

